files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/V3_MCF1024
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 15FE9B6A4B5BF3E294D0535DE9574DD2
  logicalPath: config/V3_MCF1024
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E06316F613FDA3E6444CB49EDFF7D075
- generatedChecksum: BA3FA4A1F103D298D5D3A6781FFC88E8
  logicalPath: config/V3_MCF1024
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BA3FA4A1F103D298D5D3A6781FFC88E8
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 9E6625431EABB640CE39137ECAC9DF60
  logicalPath: config/V3_MCF1024/peripheral/adchs
  name: plib_adchs.c
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: FDE6AD42344E9F456A2B9329AC34B0ED
- generatedChecksum: 89F0568EE4DC60FE8B018E3B10D1E547
  logicalPath: config/V3_MCF1024/peripheral/canfd
  name: plib_canfd1.c
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: SOURCE
  userChecksum: 89F0568EE4DC60FE8B018E3B10D1E547
- generatedChecksum: 240958B7D89740CACE01A6311D26890E
  logicalPath: config/V3_MCF1024/peripheral/cdac
  name: plib_cdac1.c
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 240958B7D89740CACE01A6311D26890E
- generatedChecksum: 558B7D7BC49AF089E9DD2B18F3293936
  logicalPath: config/V3_MCF1024/peripheral/cdac
  name: plib_cdac2.c
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 558B7D7BC49AF089E9DD2B18F3293936
- generatedChecksum: A4F4200C544E5467FC66EB7DBEABF797
  logicalPath: config/V3_MCF1024/peripheral/cdac
  name: plib_cdac3.c
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: SOURCE
  userChecksum: A4F4200C544E5467FC66EB7DBEABF797
- generatedChecksum: 80BBA536D3170C46F0C4425F2ECBFC30
  logicalPath: config/V3_MCF1024/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 80BBA536D3170C46F0C4425F2ECBFC30
- generatedChecksum: F0F77E9605002F86303776FD504751EB
  logicalPath: config/V3_MCF1024/peripheral/eeprom
  name: plib_eeprom.c
  physicalPath: peripheral/eeprom
  security: NON_SECURE
  type: SOURCE
  userChecksum: F0F77E9605002F86303776FD504751EB
- generatedChecksum: C6F5B3732C0C64BA897AE49ED4576DF2
  logicalPath: config/V3_MCF1024/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: C6F5B3732C0C64BA897AE49ED4576DF2
- generatedChecksum: A17AE69D9A690D2F115E01D25DC481EF
  logicalPath: config/V3_MCF1024/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A17AE69D9A690D2F115E01D25DC481EF
- generatedChecksum: B99480C7C5229A6A2D99F7B97D258AAA
  logicalPath: config/V3_MCF1024/peripheral/mcpwm
  name: plib_mcpwm.c
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: SOURCE
  userChecksum: FD70D916E232A4669D5C4461A9A819EF
- generatedChecksum: 84D015387757369482923F2DB9CC7292
  logicalPath: config/V3_MCF1024/peripheral/spi/spi_master
  name: plib_spi4_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 84D015387757369482923F2DB9CC7292
- generatedChecksum: E3F93E8CA137C8436705A6DCD6ED1AD6
  logicalPath: config/V3_MCF1024/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: E3F93E8CA137C8436705A6DCD6ED1AD6
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/V3_MCF1024/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 3D6F7394695ECFBF0F48E085C2935224
  logicalPath: config/V3_MCF1024
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D6F7394695ECFBF0F48E085C2935224
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/V3_MCF1024
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/V3_MCF1024
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: B2EE65C30069B4D8072900E7D5C17151
  logicalPath: config/V3_MCF1024/peripheral/adchs
  name: plib_adchs.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: B2EE65C30069B4D8072900E7D5C17151
- generatedChecksum: 5C6F0CAA7078776E1669D57D700BB66B
  logicalPath: config/V3_MCF1024/peripheral/adchs
  name: plib_adchs_common.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 5C6F0CAA7078776E1669D57D700BB66B
- generatedChecksum: 352AA2900851F05F98E6D3FCC61B0DE1
  logicalPath: config/V3_MCF1024/peripheral/canfd
  name: plib_canfd1.h
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: 352AA2900851F05F98E6D3FCC61B0DE1
- generatedChecksum: AEFE39C8E52415FE642815364C699E0C
  logicalPath: config/V3_MCF1024/peripheral/canfd
  name: plib_canfd_common.h
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: AEFE39C8E52415FE642815364C699E0C
- generatedChecksum: 685086098B2EA303F060F638C0BE1758
  logicalPath: config/V3_MCF1024/peripheral/cdac
  name: plib_cdac1.h
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: HEADER
  userChecksum: 685086098B2EA303F060F638C0BE1758
- generatedChecksum: 687743D718CCAED3CDC08D86A85048A5
  logicalPath: config/V3_MCF1024/peripheral/cdac
  name: plib_cdac2.h
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: HEADER
  userChecksum: 687743D718CCAED3CDC08D86A85048A5
- generatedChecksum: F80C81E37BF772B27E12AB4FAA51F92F
  logicalPath: config/V3_MCF1024/peripheral/cdac
  name: plib_cdac3.h
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: HEADER
  userChecksum: F80C81E37BF772B27E12AB4FAA51F92F
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/V3_MCF1024/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: B97B50D5217602B30A68AA8AA5D77BFB
  logicalPath: config/V3_MCF1024/peripheral/eeprom
  name: plib_eeprom.h
  physicalPath: peripheral/eeprom
  security: NON_SECURE
  type: HEADER
  userChecksum: B97B50D5217602B30A68AA8AA5D77BFB
- generatedChecksum: 84C8DFCC5A32ED00F039A8F15DD92B12
  logicalPath: config/V3_MCF1024/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 84C8DFCC5A32ED00F039A8F15DD92B12
- generatedChecksum: 84CA647034FE3EA461336E325B0BE459
  logicalPath: config/V3_MCF1024/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 84CA647034FE3EA461336E325B0BE459
- generatedChecksum: 5DF893C6DD8ABAE90DE45E67F2A51D7A
  logicalPath: config/V3_MCF1024/peripheral/mcpwm
  name: plib_mcpwm.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 5DF893C6DD8ABAE90DE45E67F2A51D7A
- generatedChecksum: 8C0682DB8DD38F7C09771C63347D06FF
  logicalPath: config/V3_MCF1024/peripheral/mcpwm
  name: plib_mcpwm_common.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0682DB8DD38F7C09771C63347D06FF
- generatedChecksum: 90B9F3E9BEF1F47DA15B304FF94B4D38
  logicalPath: config/V3_MCF1024/peripheral/spi/spi_master
  name: plib_spi4_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 90B9F3E9BEF1F47DA15B304FF94B4D38
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/V3_MCF1024/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 442A504503193FF627F7C0952797B7BD
  logicalPath: config/V3_MCF1024/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 442A504503193FF627F7C0952797B7BD
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/V3_MCF1024/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/V3_MCF1024
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 269B858DF1C9B5C5908925F81EA0C5CA
  logicalPath: config/V3_MCF1024
  name: p32MK1024MCM064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 269B858DF1C9B5C5908925F81EA0C5CA
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/V3_MCF1024;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/V3_MCF1024;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
